telegram_key:
  api_id: 1234567
  api_hash: api hash secreta, não deixe público seu hash e id
postgresql:
  host: localhost
  database: postgres
  user: postgres
  password: mypassword
output_dir: /home/jessica/stickers_dataset
temp_file: /tmp/{prefix}_stickersets.pkl